### ISSUE TITLE
code include path

### ISSUE THREAD

**Issue by sneaker333** [Esshahn/acme-assembly-vscode-template#6]
Just a quick question - I'm using a Mac and if I build a project which includes additional files through the use of !source then the working directory appears to be set to the project root directory and so doesn't find the additional files in the code directory. If I place the additional asm files in the root then everything works, but doesn't feel right. I've been trying to think of a neater solution but so far am not convinced of the best as they all look like compromises.

Am I missing a trick here ? I've never used ACME before (or any other C64 assembler since the 80s :-) ) I've found examples including library files using <>  instead of "" .... but no explanation where ACME expects to find those files either. Maybe this is a bit niche to expect the internet to have all the answers for a change.

Many thanks for letting me relive some teenage fun ... I just wish I was still full of the same blind ambition I had back then.

**Comment by Esshahn** [comment]
Hey @sneaker333, thanks for your question.
Here's a screenshot of a typical setup I use (also on Mac)

<img width="1465" alt="screenshot 2019-07-15 um 11 41 36" src="https://user-images.githubusercontent.com/434355/61207615-d1e2a280-a6f5-11e9-995f-1d3322059c5e.png">

So I usually have a folder "code" and a folder "resources" (sometimes it's just all in root when it's just a simple piece of code). 

File paths are always related to root, so if you have a file "intro" in a folder "code", it would be

````
!source "code/intro.asm"
````

Hope that helps,
cheers, Ingo

**Comment by sneaker333** [comment]
Hi ... many thanks for that. I had thought of that as well, but it did sort of fall into one of the 'compromises' - If I download the ACME code from here ... https://www.retrogamedev.com/downloads then I would have to edit the paths in the files first, which, being older and lazier, didn't seem like the right way. I quickly realised that I could throw the includes into the project root for it to work but thought I may be missing a trick.

Thanks for making the template available to Mac users - I had tried using the VS64 extension first and that didn't appear to work on a Mac. Now I can see if any of my 80s brain cells still exist.

I like the look of Spritemate as well ... I've been using Piskel for Godot work, but it's good to see something for C64 development.

**Comment by Esshahn** [comment]
Thanks for the kind words!  As for aging brain cells - same here, same here ;)
