### ISSUE TITLE
What is !scr?

### ISSUE THREAD

**Issue by delp** [Esshahn/acme-assembly-vscode-template#8]
Hey I'm rather new to learning 6502, but I'm not finding any info for the opcode !scr on line 79? Is there something I'm issing?

**Comment by Esshahn** [comment]
Hey Alex! `!scr` is a specific instruction of the ACME assembler, which I'm using here. 
https://sourceforge.net/projects/acme-crossass/

It's handy for displaying text since you do not need to form byte sequences for the text but can use characters instead.
